---
resources:
- name: boinc-client-official-release
  type: github-release
  icon: github
  source:
    owner: BOINC
    repository: boinc
    tag_filter: "client_release\\/.+"
- name: boinc-official-docker
  type: git
  icon: github
  source:
    uri: https://github.com/BOINC/boinc-client-docker.git
- name: pipeline-repo
  type: git
  icon: github
  source:
    uri: https://github.com/boris1993/concourse-pipelines.git
- name: my-boinc-image
  type: registry-image
  icon: docker
  source: 
    repository: "((dockerhub_username))/boinc"
    username: "((dockerhub_username))"
    password: "((dockerhub_token))"

jobs:
- name: build-image-arm64
  public: true
  build_log_retention:
    builds: 5
  plan:
  - in_parallel:
    - get: boinc-client-official-release
      trigger: true
    - get: boinc-official-docker
      trigger: true
    - get: pipeline-repo
  - load_var: tag
    file: boinc-client-official-repo
    format: trim
    reveal: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: 
          repository: concourse/oci-build-task
      inputs:
      - name: boinc-official-docker
      - name: pipeline-repo
      outputs:
      - name: arm64-image
      params:
        DOCKERFILE: pipeline-repo/boinc/Dockerfile
        IMAGE_PLATFORM: linux/arm64
      caches:
      - path: cache
      run:
        path: build
  - put: my-boinc-image
    params:
      image: image/image.tar
      bump_aliases: true
      version: "((.:tag))"
